# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa9a1b64f721735ac0d4cba284d99bdef26b7aa4b84bb29e06f6d001d31590867b05525daa3977d71c3209c6dfbd7797be74eb44340d44807546aadf42487f9c

test:
  secret_key_base: 8e32d88ef1b6331260c8af338928c2c2080ce127d1a70f863baebcce3380e69400eadd2b7281c92e8b2e11e505f4acfde32d80a3017fa35a4da7b1c0174ef568

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
